api = "0.4"

[buildpack]
id = "jkutner/web-tty"
version = "0.1.0"
name = "Web TTY"
homepage = "https://github.com/jkutner/web-tty-buildpack"
description = "Terminal access in browser over http/https"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.4.0"

  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "0.7.0"

  [[order.group]]
    id = "jkutner/wetty"
    version = "0.1.0"
