api = "0.4"

[buildpack]
id = "jkutner/wetty"
version = "0.1.0"
name = "WeTTY"
homepage = "https://github.com/jkutner/web-tty-buildpack"
description = "Installs WeTTY"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "heroku-18"
